f = open("/Users/danial/Documents/PP2_practices/practice006/demofile.txt", "a")
f.write("I am 18 years old.")
f.close()
f = open("/Users/danial/Documents/PP2_practices/practice006/demofile.txt", "r")
print(f.read())
f.close()
f = open("/Users/danial/Documents/PP2_practices/practice006/demofile.txt", "w")
f.write("OK, I deleted the content of the file and wrote this.")
f.close()
f = open("/Users/danial/Documents/PP2_practices/practice006/demofile.txt", "r")
print(f.read())
f.close()